tsbin/mlnx_bf_configure: Add ability for enabling IPsec full offload …
Mellanox/mlnx-tools pull request #24
Opened 2021-12-09 08:46 UTC by emeel97

…on boot

Added the ability to enable IPsec full offload by
setting the IPSEC_FULL_OFFLOAD flag to "yes" in the
mlnx-bf.conf file

Signed-off-by: Emeel Hakim <ehakim@nvidia.com>

2022-01-19 21:30 UTC, vladsokolovsky requested changes
Fix tabulation and rebase your commit to avoid "Merge" commit.

2022-01-19 21:30 UTC, vladsokolovsky commented on tsbin/mlnx_bf_configure
> +
Please fix the tabulation to match the rest of the file

2022-01-20 10:48 UTC, emeel97 commented on tsbin/mlnx_bf_configure
> +
done

2022-01-20 14:04 UTC, vladsokolovsky commented on tsbin/mlnx_bf_configure
> +		    if [ "X${ALLOW_SHARED_RQ}" == "Xyes" ]; then
Now these lines with wrong tabulation...

2022-01-20 14:35 UTC, vladsokolovsky approved these changes

2022-01-20 14:36 UTC, vladsokolovsky approved these changes

2022-01-20 14:57 UTC, merged